spring:
  datasource:
    url: jdbc:postgresql://192.168.129.130:5432/yu_ai_agent
    username: ai
    password: xxx
  ai:
    mcp:
      client:
        #        sse:
        #          connections:
        #            server1:
        #              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers-win.json
        toolcallback:
          enabled: true
    dashscope:
      api-key: sk-xxx
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
    vectorstore:
      pgvector:
        enabled: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10 # Optional: Maximum number of documents per batch
# searchApi
search-api:
  api-key: xxx
