spring:
  application:
    name: yz-image-search-mcp-server
  profiles:
    active: local
  ai:
    mcp:
      server:
        name: yz-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        stdio: false
        instructions: "This server provides image search capabilities."
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        # sse properties
        sse-message-endpoint: /mcp/messages
        keep-alive-interval: 30s
server:
  port: 8127

#tools:
#  image:
#    api-key: ${IMAGE_SEARCH_API_KEY:xxx}
