spring:
  ai:
    mcp:
      server:
        name: yz-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        stdio: false
        instructions: "This server provides image search capabilities."
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        # sse properties
        sse-message-endpoint: /mcp/messages
        keep-alive-interval: 30s
tools:
  image:
    api-key: FmZJNmX8QuLLGZLCk11UuYAplUgDFXkni0orLoEpf4LOfs4DcsNFk512